/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package authentication;

import config.connectDB;
import config.passwordHasher;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author HP745 G3
 */
public class forgotpass extends javax.swing.JFrame {

    /**
     * Creates new form forgotpass
     */
    public forgotpass() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ans = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        sq = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        newPass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(26, 6, 74));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/health-insurance_3035100.png"))); // NOI18N
        jLabel1.setText("Forgot Password");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        ans.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ans.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Answer"));
        jPanel2.add(ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 200, 60));

        id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "User ID"));
        jPanel2.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 200, 60));

        sq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your favorite color?", "What is your pet’s name?", "What is your mother’s first name?", "What city were you born in?", "What is your favorite food?", "What is your favorite movie?", "What is the name of your first school?" }));
        jPanel2.add(sq, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 190, 60));

        jLabel2.setText("Security Question");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        newPass.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "New Password"));
        newPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPassActionPerformed(evt);
            }
        });
        jPanel2.add(newPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 200, 60));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Confirm ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 650, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     try {

    String idText = id.getText(); 
    String selectedQuestion = sq.getSelectedItem().toString(); 
    String userAnswer = ans.getText();  
    String newPassword = newPass.getText(); 
    String hashedNewPassword = passwordHasher.hashPassword(newPassword);  


    if (idText.isEmpty() || selectedQuestion.isEmpty() || userAnswer.isEmpty() || newPassword.isEmpty()) {
        JOptionPane.showMessageDialog(null, "All fields are required!", "Missing Information", JOptionPane.WARNING_MESSAGE);
        return;
    }


    connectDB db = new connectDB();
    Connection con = db.getConnection();

 
    String fetchQuery = "SELECT security_answer FROM tbl_users WHERE id = ? AND security_question = ?";
    PreparedStatement fetchStmt = con.prepareStatement(fetchQuery);
    fetchStmt.setString(1, idText);  
    fetchStmt.setString(2, selectedQuestion);  
    ResultSet rs = fetchStmt.executeQuery();

  
    if (rs.next()) {
        String storedHashedAnswer = rs.getString("security_answer"); 


        String hashedInputAnswer = passwordHasher.hashPassword(userAnswer);

 
        if (storedHashedAnswer.equals(hashedInputAnswer)) {
      
            String updateQuery = "UPDATE tbl_users SET pass = ? WHERE id = ?";
            PreparedStatement updateStmt = con.prepareStatement(updateQuery);
            updateStmt.setString(1, hashedNewPassword);  
            updateStmt.setString(2, idText); 
            int updateResult = updateStmt.executeUpdate();

            
            if (updateResult == 1) {
                JOptionPane.showMessageDialog(null, "Password successfully reset!");
                this.dispose(); 
            } else {
                JOptionPane.showMessageDialog(null, "Failed to update password.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Incorrect answer to the security question.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "No matching user found for the given ID and security question.");
    }


    rs.close();
    fetchStmt.close();
    con.close();

} catch (SQLException | NoSuchAlgorithmException ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(null, "Error resetting password!", "Error", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgotpass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ans;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField newPass;
    private javax.swing.JComboBox<String> sq;
    // End of variables declaration//GEN-END:variables
}
